name: walk_dog_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_flavor: ^3.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.4
  formz: ^0.6.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  injectable: ^2.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^1.3.0
  shared_preferences: ^2.0.20
  story_view: ^0.14.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_screenutil: ^5.8.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.3.0
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding.jpeg
    - assets/images/google-icon.png
